# Copy the code for initializing the repo
COPY ./_private /working/_private

# Install required node packages
WORKDIR /working/_private/node
RUN npm install

# Set the working directory
RUN mkdir /working/workspace
WORKDIR /working/workspace

ENV PATH "/working/_private/bin:$PATH"
